spring:
  application:
    name: springboot

  jpa:
    show-sql: true
    open-in-view: false
    database-platform: org.hibernate.dialect.MySQL5Dialect
    properties:
      hibernate.format_sql: true
    hibernate:
      ddl-auto: create

  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/crud?verifyServerCertificate=false&useSSL=false&requireSSL=false&useLegacyDatetimeCode=false&amp&serverTimezone=UTC
    username: root
    password: root

  mvc:
    hiddenmethod:
      filter:
        enabled: true

  thymeleaf:
    enabled: true
    enable-spring-el-compiler: true
    prefix: /WEB-INF/views/
    suffix: .html

server:
  port: 8080